spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GAUbMxnfC6Jz9C8TDpa
      secret-key: 0w3VJMxAMGawbGf1gXIAEtvSBHWrG6
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-luodong


  application:
    name: gulimall-third-party

server:
  port: 30000
